pipelines:
  pipe1:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rajat965ng/proximity-labs-challenge.git
    stages:
    - build: # name of stage
       jobs:
         build: # name of the job
          tasks:
          - exec: # indicates type of task
             command: ls -la
